# Annotated Bibliography

```{block, type = "rmdgoal"}
**Goal:** Identify the state of the literature on your topic.
```

```{block, type = "rmdpersonnel"}
**Personnel:** This vignette should be completed by students in **SOC 5050** only.
```

```{block, type = "rmdpre"}
**Pre-requisties:** Complete this vignette after reciving feedback from Chris on vignette 1.
```

```{block, type = "rmdskills"}
**Skills:** There are no course-specific skills for this vignette.
```

```{block, type = "rmddue"}
**Required Due Date:** Lecture 7 (October 8^th^)
```

```{block, type = "rmddeliver"}
**Deliverables:** A markdown file (`.md`) with properly formatted citations and evalutative assessments of each source; your spreadsheet documenting the search process.
```

## What is an Annotated Bibliography?
An **Annotated Bibliography** is one approach for documenting your research on a topic. It should be constructed using a thorough, systematic **literature search** of the [peer reviewed](https://library.sdsu.edu/research-services/research-help/peer-reviewed-articles) literature on your topic. We are interested primarily in the peer reviewed literature because we we want to understand the scholarly debate that has unfolded about our topic. The peer review process is also one indicator of quality. 

We typically think of peer review as falling into two categories - books and journal articles. While the process for reviewing books is different from articles, academic books are typically sent out for review before they are published by the publisher. Peer reviewed books are typically published by either a university press (e.g. Oxford University Press or The University of California Press) or by a publishing house that specializes in academic content (e.g. John Wiley & Sons).

Journal articles that are peer reviewed will be published in an academic journal. There are [many journals that publish sociological content](https://gmusocgrads.wordpress.com/development/journals/), along with others that publish more broadly in the social sciences (*Social Science & Medicine* is a great example). Beaware that not all journals are created equal - there is a whole group of so-called ["predatory" journals](https://beallslist.weebly.com) (along with [fake conferences](https://www.nytimes.com/2016/12/29/upshot/fake-academe-looking-much-like-the-real-thing.html)) that [capitalize on the "publish or perish" culture of academia](https://www.nytimes.com/2017/10/30/science/predatory-journals-academics.html) as well as the relative isolation of many scholars in developing countries.



## Conducting the Literature Search


## Evaluating Sources

