# (PART) Data Analysis {-}

# Descriptive Statistics

```{block, type = "rmdgoal"}
**Goal:** Produce appropriate summary statistics for each variable in your study.
```

```{block, type = "rmdpersonnel"}
**Personnel:** This vignette should be completed by **all** students. 
```

```{block, type = "rmdpre"}
**Pre-requisties:** This vignette should be started _after_ Vignette 4's initial completion.
```

```{block, type = "rmdskills"}
**Skills:** Lecture 3
```

```{block, type = "rmddue"}
**_Suggested_ Due Date:** Lecture 8 (October 15^th^)
```

```{block, type = "rmddeliver"}
**Deliverables:** A well-formatted notebook in the `docs/` folder that uses literate programming to produce the output needed for a descriptive statistics table, which should be saved in the `results/` folder.
```

## Descriptive Statistics Overview

### Analysis Development

All descriptive statistics work should be done in a single notebook that you clarify and expand over time. Your final results for your presentation (and paper if applicable) should be stored in the `results/` folder.

### Initial Analyses

As with other parts of the final project, this section will require some iteration. Initially, you should use the `skimr` package to calculate descriptive statistics for all of your study variables after you have done some initial [data cleaning](/data-cleaning.html). The `skimr` results are best used for initial data exploration but should not be your only approach. Make sure to use other packages, like `moments`, to calculate additional descriptive statistics as needed for continuous variables. Use these initial calculations to make decisions about additional data cleaning and variable selection.

During this initial phase, you should also use `naniar` to produce an analysis of missing data in your data set. Your final presentation (and paper if applicable) will need to describe any patterns of missing data and their possible impact on your results.

### Final Analyses

Once you have a finalized set of study variables, your presentation (and paper if applicable) should include a descriptive statistics for all of the final variables used in your project. Since all of these variables will be either logical, ordinal, or continuous, you need only report the means for each of these variables. If a particular categorical variable is important to your analysis, you could also report the frequencies and percentages for this variable in a separate table. Check out recent articles in the *<a href="https://www.journals.uchicago.edu/loi/ajs" target="_blank">American Journal of Sociology</a>* for examples of different ways to present descriptive statistics.
